CREATE TABLE TB_BOARD
(
    IDX int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PARENT_IDX int,
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(4000) NOT NULL,
    HIT_CNT int NOT NULL,
    DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
    CREA_DTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREA_ID VARCHAR(30) NOT NULL
);