-- DROP TABLE TB_BOARD;

CREATE TABLE TB_BOARD
(
    IDX INT not null auto_increment,
    PARENT_IDX INT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENTS VARCHAR(4000) NOT NULL,
    HIT_CNT INT NOT NULL,
    DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
    CREA_DTM DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREA_ID VARCHAR(30) NOT NULL,
    PRIMARY KEY(IDX)
);

SELECT * FROM TB_BOARD;